version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: