# Использование образа ubuntu:20.04 в качестве базового
???

# Обновление пакетов и установка Python
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean

# Создание директории для приложения
???

# Копирование Python-приложение в рабочую директорию
???

# Команда запуска приложения
CMD ["python3", "app.py"]