version: '3.8'

services:
  web:
    image: nginx:latest
    networks:
      - my_overlay_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
    networks:
      - my_overlay_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  my_overlay_network:
    driver: overlay