version: '3.8'

services:
  prometheus:
    image: prom/???:latest
    volumes:
      - ???:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/???:latest
    volumes:
      - ???:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data: