version: '3.8'

services:
  ???:
    image: nginx:latest
    networks:
      - my_network

  ???:
    image: python:3.8-slim
    networks:
      - my_network

  ???:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    networks:
      - my_network

networks:
  my_network:
    driver: bridge