version: '3.8'

services:
  postgres:
    image: ???
    environment:
      POSTGRES_DB: ???
      POSTGRES_USER: ???
      POSTGRES_PASSWORD: ???
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ???

volumes:
  pgdata:

networks:
  mynetwork: